### ISSUE TITLE
Question about person pooling

### ISSUE THREAD

**Issue by dingli-dean** [cvlab-epfl/social-scene-understanding#4]
In this repo,I've noticed that person pooling is applied among all 12 members in the group,while the 2-group pooling has been used for this task,in order to improve the performance.So,I want to know whether the result you have reported in the CVPR2017 paper is based on 2-group pooling or max-pooling among all individuals?

**Comment by psycharo-zz** [comment]
It was max-pooled over all the individuals. It can indeed be helpful to pool over 2 groups separately.
