### ISSUE TITLE
Questions about distance computation in matching 

### ISSUE THREAD

**Issue by dingli-dean** [cvlab-epfl/social-scene-understanding#5]
In person matching process,you have ultilized 'nnutil.cdist()' to compute the distance between 'boxes[t-1]' and 'boxes[t]'.But, the aim of this is to get the idxs for matching and find the correct 'state_prev'.Thus, it should be 'nnutil.cdist(boxes[t], boxes[t-1])' in line 227 of 'volleyball_train_stage_b.py', right?
Besides, the shape of 'boxes_in' is [B, T, N, 4],while the input of function '_construct_sequence(batch)' is a batch of data,and its shape should be [T, N, *](line 218 of 'volleyball_train_stage_b.py'),could you check it again?

**Comment by dingli-dean** [comment]
Thanks a lot and look forward your reply.

**Comment by psycharo-zz** [comment]
As for the first question, you are of course correct: I have uploaded an older buggy version when converting from my notebooks, the softmax computation there was also wrong. Thanks for the catch!
As for the second one: we use `_construct_sequence()` function with `tf.map_fn`, which means that it take a single temporal sequence. The parameter `batch` is a bit misleading, it is a "temporal" batch.

**Comment by dingli-dean** [comment]
Got it.Could you explain why the softmax computation is wrong in details?Thank you.

**Comment by psycharo-zz** [comment]
soft matching essentially weights the vectors from the previous step based on the distance to the current step: the smaller the distance, the more weight one of the previous vectors get. Thus it should be `softmax(-distance)`, instead of `softmax(distance)`. Hope this helps.

**Comment by dingli-dean** [comment]
Thank you.

**Comment by dingli-dean** [comment]
Besides,excuse me, do you have timeline for review the older version and upload a newer version?

**Comment by psycharo-zz** [comment]
I already fixed those in-place, but unfortunately will not have time in the nearest future to double-check all the code.
